"""add cascade delete for notes

Revision ID: 2b360cb044cb
Revises: 7b9260771ec1
Create Date: 2026-09-09 18:12:45.991372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b360cb044cb'
down_revision: Union[str, Sequence[str], None] = '7b9260771ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notes_task_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_task_id_fkey'), 'notes', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
